# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do |lane, options|
    # 拉取最新代码
    git_pull
  end


  desc "查看当前版本号"
  lane :version do
    version_to_string = "current podspec version is v#{version_get_podspec}"
    UI.error      version_to_string 
    UI.important  version_to_string 
    UI.success    version_to_string
    UI.deprecated version_to_string
  end

  desc "一键更新私有仓库到公有仓库"
  lane :upgrade do |options|
    # 必须输入版本号
    return unless options[:tag]
    # 确保当前是 master 分支
    ensure_git_branch
    # 检查 Podspec 有效性
    pod_lib_lint(allow_warnings: true)
    #修改 podspec 版本号
    version_bump_podspec(version_number: options[:tag]) 
    # commit
    commit(message: options[:message] || "update version to #{options[:tag]}")
    # 添加 tag
    add_git_tag(tag: options[:tag]) 
    # push 本地 tags
    push_git_tags 
    # push podspec 到仓库
    pod_push(allow_warnings: true) 
  end

  desc "提交代码到远程仓库"
  lane :commit do |options|
    # 必须输入message信息
    return unless options[:message]
    # git add .
    git_add
    # git commit -m "xxx"
    git_commit(path: ".", message: options[:message]) 
    # git push origin master
    push_to_git_remote 
  end

end
